apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-proj-deployment
  name: php-proj-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30005
  selector:
    app: php-proj-deployment
  type: NodePort
